version: 2.1

orbs:
  docker: circleci/docker@2.0.3

workflows:
  docker:
    jobs:
      - docker/publish:
          name: "linux-builder"
          image: sensu/sensu-release
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}-linux-builder
          dockerfile: dockerfiles/linux-builder/Dockerfile
      - docker/publish:
          name: "packagecloud-pruner"
          image: sensu/sensu-release
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}-packagecloud-pruner
          dockerfile: dockerfiles/packagecloud-pruner/Dockerfile
