version: 2.1

orbs:
  docker: circleci/docker@1.4.0

workflows:
  docker:
    jobs:
      - docker/publish:
          image: sensu/justin-testing
          tag: alpine-builder-$CIRCLE_SHA1
          dockerfile: dockerfiles/linux-builder/Dockerfile
      - docker/publish:
          image: sensu/justin-testing
          tag: redhat7-builder-$CIRCLE_SHA1
          dockerfile: dockerfiles/rhel7-builder/Dockerfile
