version: 2.1

orbs:
  docker: circleci/docker@1.4.0

workflows:
  docker:
    jobs:
      - docker/publish:
          image: sensu/justin-testing
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}-linux-builder
          dockerfile: dockerfiles/linux-builder/Dockerfile
      - docker/publish:
          image: sensu/justin-testing
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}-redhat7-builder
          dockerfile: dockerfiles/rhel7-builder/Dockerfile
      - docker/publish:
          image: sensu/justin-testing
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}-redhat8-builder
          dockerfile: dockerfiles/rhel8-builder/Dockerfile
      - docker/publish:
          image: sensu/justin-testing
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}-packagecloud-pruner
          dockerfile: dockerfiles/packagecloud-pruner/Dockerfile
